title: LFESS Working Group Template
description: LFESS Working Group Template, using a Jeykll site deployed via GitHub Pages using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://wg-template.lfess.energy
